# Generated by Django 2.2.5 on 2019-09-17 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
